# This package only exists to avoid circular dependencies during cargo publish:
# Alembic-bpf-loader-program -> Alembic-program-test -> Alembic-bpf-loader-program

[package]
name = "Alembic-bpf-loader-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
Alembic-bpf-loader-program = { workspace = true }
Alembic-program-test = { workspace = true }
Alembic-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
