[package]
name = "Alembic-loader-v4-program"
description = "Alembic Loader v4"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
Alembic-measure = { workspace = true }
Alembic-program-runtime = { workspace = true }
Alembic-sdk = { workspace = true }
Alembic_rbpf = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }

[lib]
crate-type = ["lib"]
name = "Alembic_loader_v4_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
