[package]
name = "Alembic-udp-client"
description = "Alembic UDP Client"
documentation = "https://docs.rs/Alembic-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
Alembic-connection-cache = { workspace = true }
Alembic-net-utils = { workspace = true }
Alembic-sdk = { workspace = true }
Alembic-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
