[package]
name = "Alembic-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/Alembic-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
Alembic-clap-utils = { workspace = true }
Alembic-cli-config = { workspace = true }
Alembic-remote-wallet = { workspace = true, features = ["default"] }
Alembic-rpc-client = { workspace = true, features = ["default"] }
Alembic-rpc-client-api = { workspace = true }
Alembic-sdk = { workspace = true }
Alembic-stake-program = { workspace = true }
Alembic-version = { workspace = true }

[dev-dependencies]
Alembic-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
