[package]
name = "Alembic-tokens"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/Alembic-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = "2.33.0"
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
indexmap = { workspace = true }
indicatif = { workspace = true }
pickledb = { workspace = true, features = ["yaml"] }
serde = { workspace = true, features = ["derive"] }
Alembic-account-decoder = { workspace = true }
Alembic-clap-utils = { workspace = true }
Alembic-cli-config = { workspace = true }
Alembic-remote-wallet = { workspace = true, features = ["default"] }
Alembic-rpc-client = { workspace = true, features = ["default"] }
Alembic-rpc-client-api = { workspace = true }
Alembic-sdk = { workspace = true }
Alembic-transaction-status = { workspace = true }
Alembic-version = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
Alembic-logger = { workspace = true }
Alembic-streamer = { workspace = true }
Alembic-test-validator = { workspace = true }
