[package]
name = "Alembic-svm"
description = "Alembic SVM"
documentation = "https://docs.rs/Alembic-svm"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
itertools = { workspace = true }
log = { workspace = true }
percentage = { workspace = true }
Alembic-bpf-loader-program = { workspace = true }
Alembic-frozen-abi = { workspace = true }
Alembic-frozen-abi-macro = { workspace = true }
Alembic-loader-v4-program = { workspace = true }
Alembic-measure = { workspace = true }
Alembic-metrics = { workspace = true }
Alembic-program-runtime = { workspace = true }
Alembic-sdk = { workspace = true }
Alembic-system-program = { workspace = true }

[lib]
crate-type = ["lib"]
name = "Alembic_svm"

[dev-dependencies]
bincode = { workspace = true }
Alembic-logger = { workspace = true }
Alembic-sdk = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }

[features]
dev-context-only-utils = []
