[package]
name = "Alembic-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/Alembic-ledger-tool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true }
chrono = { workspace = true, features = ["default"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
csv = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
histogram = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
Alembic-account-decoder = { workspace = true }
Alembic-accounts-db = { workspace = true }
Alembic-bpf-loader-program = { workspace = true }
Alembic-clap-utils = { workspace = true }
Alembic-cli-output = { workspace = true }
Alembic-core = { workspace = true }
Alembic-cost-model = { workspace = true }
Alembic-entry = { workspace = true }
Alembic-geyser-plugin-manager = { workspace = true }
Alembic-gossip = { workspace = true }
Alembic-ledger = { workspace = true }
Alembic-logger = { workspace = true }
Alembic-measure = { workspace = true }
Alembic-program-runtime = { workspace = true }
Alembic-rpc = { workspace = true }
Alembic-runtime = { workspace = true, features = ["dev-context-only-utils"] }
Alembic-sdk = { workspace = true }
Alembic-stake-program = { workspace = true }
Alembic-storage-bigtable = { workspace = true }
Alembic-streamer = { workspace = true }
Alembic-transaction-status = { workspace = true }
Alembic-unified-scheduler-pool = { workspace = true }
Alembic-version = { workspace = true }
Alembic-vote-program = { workspace = true }
Alembic_rbpf = { workspace = true, features = ["debugger"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
bytecount = { workspace = true }

[features]
dev-context-only-utils = []

[target."cfg(unix)".dependencies]
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
