[package]
name = "Alembic-system-program"
description = "Alembic System program"
documentation = "https://docs.rs/Alembic-system-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
Alembic-program-runtime = { workspace = true }
Alembic-sdk = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
Alembic-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "Alembic_system_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
